# Generated by Django 5.2.1 on 2025-11-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='area',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='areas',
            field=models.ManyToManyField(to='core.areamunicipal', verbose_name='Áreas Asignadas'),
        ),
        migrations.AlterField(
            model_name='areamunicipal',
            name='slug',
            field=models.SlugField(blank=True, help_text='Se genera automáticamente', max_length=100, unique=True),
        ),
    ]
